# Created by and for Qt Creator. This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = WalkingSim

HEADERS = \
   $$PWD/include/glm/detail/_features.hpp \
   $$PWD/include/glm/detail/_fixes.hpp \
   $$PWD/include/glm/detail/_noise.hpp \
   $$PWD/include/glm/detail/_swizzle.hpp \
   $$PWD/include/glm/detail/_swizzle_func.hpp \
   $$PWD/include/glm/detail/_vectorize.hpp \
   $$PWD/include/glm/detail/func_common.hpp \
   $$PWD/include/glm/detail/func_exponential.hpp \
   $$PWD/include/glm/detail/func_geometric.hpp \
   $$PWD/include/glm/detail/func_integer.hpp \
   $$PWD/include/glm/detail/func_matrix.hpp \
   $$PWD/include/glm/detail/func_packing.hpp \
   $$PWD/include/glm/detail/func_trigonometric.hpp \
   $$PWD/include/glm/detail/func_vector_relational.hpp \
   $$PWD/include/glm/detail/precision.hpp \
   $$PWD/include/glm/detail/setup.hpp \
   $$PWD/include/glm/detail/type_float.hpp \
   $$PWD/include/glm/detail/type_gentype.hpp \
   $$PWD/include/glm/detail/type_half.hpp \
   $$PWD/include/glm/detail/type_int.hpp \
   $$PWD/include/glm/detail/type_mat.hpp \
   $$PWD/include/glm/detail/type_mat2x2.hpp \
   $$PWD/include/glm/detail/type_mat2x3.hpp \
   $$PWD/include/glm/detail/type_mat2x4.hpp \
   $$PWD/include/glm/detail/type_mat3x2.hpp \
   $$PWD/include/glm/detail/type_mat3x3.hpp \
   $$PWD/include/glm/detail/type_mat3x4.hpp \
   $$PWD/include/glm/detail/type_mat4x2.hpp \
   $$PWD/include/glm/detail/type_mat4x3.hpp \
   $$PWD/include/glm/detail/type_mat4x4.hpp \
   $$PWD/include/glm/detail/type_vec.hpp \
   $$PWD/include/glm/detail/type_vec1.hpp \
   $$PWD/include/glm/detail/type_vec2.hpp \
   $$PWD/include/glm/detail/type_vec3.hpp \
   $$PWD/include/glm/detail/type_vec4.hpp \
   $$PWD/include/glm/gtc/bitfield.hpp \
   $$PWD/include/glm/gtc/color_space.hpp \
   $$PWD/include/glm/gtc/constants.hpp \
   $$PWD/include/glm/gtc/epsilon.hpp \
   $$PWD/include/glm/gtc/functions.hpp \
   $$PWD/include/glm/gtc/integer.hpp \
   $$PWD/include/glm/gtc/matrix_access.hpp \
   $$PWD/include/glm/gtc/matrix_integer.hpp \
   $$PWD/include/glm/gtc/matrix_inverse.hpp \
   $$PWD/include/glm/gtc/matrix_transform.hpp \
   $$PWD/include/glm/gtc/noise.hpp \
   $$PWD/include/glm/gtc/packing.hpp \
   $$PWD/include/glm/gtc/quaternion.hpp \
   $$PWD/include/glm/gtc/random.hpp \
   $$PWD/include/glm/gtc/reciprocal.hpp \
   $$PWD/include/glm/gtc/round.hpp \
   $$PWD/include/glm/gtc/type_aligned.hpp \
   $$PWD/include/glm/gtc/type_precision.hpp \
   $$PWD/include/glm/gtc/type_ptr.hpp \
   $$PWD/include/glm/gtc/ulp.hpp \
   $$PWD/include/glm/gtc/vec1.hpp \
   $$PWD/include/glm/gtx/associated_min_max.hpp \
   $$PWD/include/glm/gtx/bit.hpp \
   $$PWD/include/glm/gtx/closest_point.hpp \
   $$PWD/include/glm/gtx/color_space.hpp \
   $$PWD/include/glm/gtx/color_space_YCoCg.hpp \
   $$PWD/include/glm/gtx/common.hpp \
   $$PWD/include/glm/gtx/compatibility.hpp \
   $$PWD/include/glm/gtx/component_wise.hpp \
   $$PWD/include/glm/gtx/dual_quaternion.hpp \
   $$PWD/include/glm/gtx/euler_angles.hpp \
   $$PWD/include/glm/gtx/extend.hpp \
   $$PWD/include/glm/gtx/extended_min_max.hpp \
   $$PWD/include/glm/gtx/fast_exponential.hpp \
   $$PWD/include/glm/gtx/fast_square_root.hpp \
   $$PWD/include/glm/gtx/fast_trigonometry.hpp \
   $$PWD/include/glm/gtx/gradient_paint.hpp \
   $$PWD/include/glm/gtx/handed_coordinate_space.hpp \
   $$PWD/include/glm/gtx/hash.hpp \
   $$PWD/include/glm/gtx/integer.hpp \
   $$PWD/include/glm/gtx/intersect.hpp \
   $$PWD/include/glm/gtx/io.hpp \
   $$PWD/include/glm/gtx/log_base.hpp \
   $$PWD/include/glm/gtx/matrix_cross_product.hpp \
   $$PWD/include/glm/gtx/matrix_decompose.hpp \
   $$PWD/include/glm/gtx/matrix_interpolation.hpp \
   $$PWD/include/glm/gtx/matrix_major_storage.hpp \
   $$PWD/include/glm/gtx/matrix_operation.hpp \
   $$PWD/include/glm/gtx/matrix_query.hpp \
   $$PWD/include/glm/gtx/matrix_transform_2d.hpp \
   $$PWD/include/glm/gtx/mixed_product.hpp \
   $$PWD/include/glm/gtx/norm.hpp \
   $$PWD/include/glm/gtx/normal.hpp \
   $$PWD/include/glm/gtx/normalize_dot.hpp \
   $$PWD/include/glm/gtx/number_precision.hpp \
   $$PWD/include/glm/gtx/optimum_pow.hpp \
   $$PWD/include/glm/gtx/orthonormalize.hpp \
   $$PWD/include/glm/gtx/perpendicular.hpp \
   $$PWD/include/glm/gtx/polar_coordinates.hpp \
   $$PWD/include/glm/gtx/projection.hpp \
   $$PWD/include/glm/gtx/quaternion.hpp \
   $$PWD/include/glm/gtx/range.hpp \
   $$PWD/include/glm/gtx/raw_data.hpp \
   $$PWD/include/glm/gtx/rotate_normalized_axis.hpp \
   $$PWD/include/glm/gtx/rotate_vector.hpp \
   $$PWD/include/glm/gtx/scalar_multiplication.hpp \
   $$PWD/include/glm/gtx/scalar_relational.hpp \
   $$PWD/include/glm/gtx/simd_mat4.hpp \
   $$PWD/include/glm/gtx/simd_quat.hpp \
   $$PWD/include/glm/gtx/simd_vec4.hpp \
   $$PWD/include/glm/gtx/spline.hpp \
   $$PWD/include/glm/gtx/std_based_type.hpp \
   $$PWD/include/glm/gtx/string_cast.hpp \
   $$PWD/include/glm/gtx/transform.hpp \
   $$PWD/include/glm/gtx/transform2.hpp \
   $$PWD/include/glm/gtx/type_aligned.hpp \
   $$PWD/include/glm/gtx/type_trait.hpp \
   $$PWD/include/glm/gtx/vector_angle.hpp \
   $$PWD/include/glm/gtx/vector_query.hpp \
   $$PWD/include/glm/gtx/wrap.hpp \
   $$PWD/include/glm/simd/common.h \
   $$PWD/include/glm/simd/exponential.h \
   $$PWD/include/glm/simd/geometric.h \
   $$PWD/include/glm/simd/integer.h \
   $$PWD/include/glm/simd/matrix.h \
   $$PWD/include/glm/simd/packing.h \
   $$PWD/include/glm/simd/platform.h \
   $$PWD/include/glm/simd/trigonometric.h \
   $$PWD/include/glm/simd/vector_relational.h \
   $$PWD/include/glm/common.hpp \
   $$PWD/include/glm/exponential.hpp \
   $$PWD/include/glm/ext.hpp \
   $$PWD/include/glm/fwd.hpp \
   $$PWD/include/glm/geometric.hpp \
   $$PWD/include/glm/glm.hpp \
   $$PWD/include/glm/integer.hpp \
   $$PWD/include/glm/mat2x2.hpp \
   $$PWD/include/glm/mat2x3.hpp \
   $$PWD/include/glm/mat2x4.hpp \
   $$PWD/include/glm/mat3x2.hpp \
   $$PWD/include/glm/mat3x3.hpp \
   $$PWD/include/glm/mat3x4.hpp \
   $$PWD/include/glm/mat4x2.hpp \
   $$PWD/include/glm/mat4x3.hpp \
   $$PWD/include/glm/mat4x4.hpp \
   $$PWD/include/glm/matrix.hpp \
   $$PWD/include/glm/packing.hpp \
   $$PWD/include/glm/trigonometric.hpp \
   $$PWD/include/glm/vec2.hpp \
   $$PWD/include/glm/vec3.hpp \
   $$PWD/include/glm/vec4.hpp \
   $$PWD/include/glm/vector_relational.hpp \
   $$PWD/include/imconfig.h \
   $$PWD/include/imgui.h \
   $$PWD/include/imgui_internal.h \
   $$PWD/include/stb_rect_pack.h \
   $$PWD/include/stb_textedit.h \
   $$PWD/include/stb_truetype.h \
   $$PWD/src/engine/render/imgui/imgui_sre.hpp \
   $$PWD/src/engine/render/impl/CPPShim.hpp \
   $$PWD/src/engine/render/impl/Export.hpp \
   $$PWD/src/engine/render/impl/GL.hpp \
   $$PWD/src/engine/render/BlendType.hpp \
   $$PWD/src/engine/render/Camera.hpp \
   $$PWD/src/engine/render/Debug.hpp \
   $$PWD/src/engine/render/Light.hpp \
   $$PWD/src/engine/render/LightType.hpp \
   $$PWD/src/engine/render/Mesh.hpp \
   $$PWD/src/engine/render/MeshTopology.hpp \
   $$PWD/src/engine/render/RenderStats.h \
   $$PWD/src/engine/render/Shader.hpp \
   $$PWD/src/engine/render/SimpleRenderEngine.hpp \
   $$PWD/src/engine/render/Texture.hpp

SOURCES = \
   $$PWD/cmake/FindGLEW.cmake \
   $$PWD/cmake/FindGLM.cmake \
   $$PWD/cmake/FindSDL2.cmake \
   $$PWD/cmake/FindSDL2_IMAGE.cmake \
   $$PWD/cmake/FindSDL2_MIXER.cmake \
   $$PWD/cmake/FindSDL2_ttf.cmake \
   $$PWD/cmake/FindSRE.cmake \
   $$PWD/include/glm/detail/dummy.cpp \
   $$PWD/include/glm/detail/glm.cpp \
   $$PWD/src/engine/render/imgui/imgui.cpp \
   $$PWD/src/engine/render/imgui/imgui_draw.cpp \
   $$PWD/src/engine/render/imgui/imgui_sre.cpp \
   $$PWD/src/engine/render/Camera.cpp \
   $$PWD/src/engine/render/Debug.cpp \
   $$PWD/src/engine/render/Light.cpp \
   $$PWD/src/engine/render/Mesh.cpp \
   $$PWD/src/engine/render/Shader.cpp \
   $$PWD/src/engine/render/SimpleRenderEngine.cpp \
   $$PWD/src/engine/render/Texture.cpp \
   $$PWD/src/main.cpp \
   $$PWD/CMakeLists.txt

INCLUDEPATH = \
    $$PWD/include \
    $$PWD/include/glm/simd \
    $$PWD/src/engine/render

#DEFINES = 

